export interface UseCaseDefinition {
  id: string;
  name: string;
  stage: "TOFU" | "MOFU" | "BOFU" | "POST_SALE" | "INTERNAL" | "VERTICAL" | "FORMAT";
  focus: string;
}

export const USE_CASES: UseCaseDefinition[] = [
  { id: "industry_trend_validation", name: "Industry Trend Validation", stage: "TOFU", focus: "How the customer navigated a macro shift." },
  { id: "problem_challenge_identification", name: "Problem/Challenge Identification", stage: "TOFU", focus: "Day-in-the-life pain point before the solution." },
  { id: "digital_transformation_modernization", name: "Digital Transformation Journey", stage: "TOFU", focus: "Modernization outcomes and transformation milestones." },
  { id: "regulatory_compliance_challenges", name: "Regulatory/Compliance Challenge", stage: "TOFU", focus: "Compliance constraints and how they were resolved." },
  { id: "market_expansion", name: "Market Expansion", stage: "TOFU", focus: "Expansion to new geographies or segments." },
  { id: "thought_leadership_cocreation", name: "Thought Leadership Co-Creation", stage: "TOFU", focus: "Joint insights/research with the customer." },
  { id: "product_capability_deepdive", name: "Product Capability Deep-Dive", stage: "MOFU", focus: "Feature/platform capability in real use." },
  { id: "competitive_displacement", name: "Competitive Displacement", stage: "MOFU", focus: "Migration off a named competitor." },
  { id: "integration_interoperability", name: "Integration/Interoperability", stage: "MOFU", focus: "How the solution integrates into existing stack." },
  { id: "implementation_onboarding", name: "Implementation/Onboarding", stage: "MOFU", focus: "Rollout plan, time-to-value, onboarding friction." },
  { id: "security_compliance_governance", name: "Security/Compliance/Governance", stage: "MOFU", focus: "Security and governance proof points in practice." },
  { id: "customization_configurability", name: "Customization/Configurability", stage: "MOFU", focus: "Unique workflow tailoring and flexibility." },
  { id: "multi_product_cross_sell", name: "Multi-Product Adoption", stage: "MOFU", focus: "Land-and-expand across multiple products." },
  { id: "partner_ecosystem_solution", name: "Partner/Ecosystem Solution", stage: "MOFU", focus: "SI/reseller/ISV role in success." },
  { id: "total_cost_of_ownership", name: "Total Cost of Ownership", stage: "MOFU", focus: "Pricing model and TCO validation." },
  { id: "pilot_to_production", name: "Pilot to Production", stage: "MOFU", focus: "POC journey and production rollout evidence." },
  { id: "roi_financial_outcomes", name: "ROI/Financial Outcomes", stage: "BOFU", focus: "Hard ROI, payback period, savings/revenue." },
  { id: "quantified_operational_metrics", name: "Quantified Operational Metrics", stage: "BOFU", focus: "Time saved, efficiency gains, error reduction." },
  { id: "executive_strategic_impact", name: "Executive Strategic Impact", stage: "BOFU", focus: "Board or C-suite strategic impact framing." },
  { id: "risk_mitigation_continuity", name: "Risk Mitigation and Continuity", stage: "BOFU", focus: "Risk reduction and continuity outcomes." },
  { id: "deployment_speed", name: "Deployment Speed", stage: "BOFU", focus: "Speed vs initial deployment expectations." },
  { id: "vendor_selection_criteria", name: "Vendor Selection Criteria", stage: "BOFU", focus: "Why vendor was chosen over alternatives." },
  { id: "procurement_experience", name: "Procurement Experience", stage: "BOFU", focus: "Contracting and procurement journey." },
  { id: "renewal_partnership_evolution", name: "Renewal and Long-Term Partnership", stage: "POST_SALE", focus: "Renewal signals and relationship maturity." },
  { id: "upsell_cross_sell_expansion", name: "Upsell/Cross-Sell Expansion", stage: "POST_SALE", focus: "Expansion path and incremental value." },
  { id: "customer_success_support", name: "Customer Success and Support", stage: "POST_SALE", focus: "CS/support quality and outcomes." },
  { id: "training_enablement_adoption", name: "Training and Enablement", stage: "POST_SALE", focus: "Enablement programs and adoption lift." },
  { id: "community_advisory_participation", name: "Community/Advisory Participation", stage: "POST_SALE", focus: "Community engagement and advocacy." },
  { id: "co_innovation_product_feedback", name: "Co-Innovation/Product Feedback", stage: "POST_SALE", focus: "Roadmap influence and feedback loop." },
  { id: "change_management_champion_dev", name: "Change Management/Champions", stage: "POST_SALE", focus: "Internal champion growth and change mgmt." },
  { id: "scaling_across_org", name: "Scaling Across Organization", stage: "POST_SALE", focus: "Usage growth across teams/geographies." },
  { id: "platform_governance_coe", name: "Platform Governance/CoE", stage: "POST_SALE", focus: "Governance model and center-of-excellence setup." },
  { id: "sales_enablement", name: "Sales Enablement", stage: "INTERNAL", focus: "Objections, competitive intel, deal strategy." },
  { id: "lessons_learned_implementation", name: "Lessons Learned", stage: "INTERNAL", focus: "What failed and how it was fixed." },
  { id: "cross_functional_collaboration", name: "Cross-Functional Collaboration", stage: "INTERNAL", focus: "Sales + CS + product + engineering dynamics." },
  { id: "voice_of_customer_product", name: "Voice of Customer to Product", stage: "INTERNAL", focus: "Customer insights feeding product roadmap." },
  { id: "pricing_packaging_validation", name: "Pricing/Packaging Validation", stage: "INTERNAL", focus: "Pricing iterations and evidence." },
  { id: "churn_save_winback", name: "Churn Save and Win-Back", stage: "INTERNAL", focus: "Retention recovery and save stories." },
  { id: "deal_anatomy", name: "Deal Anatomy", stage: "INTERNAL", focus: "How deal was sourced, structured, and closed." },
  { id: "customer_health_sentiment", name: "Customer Health/Sentiment", stage: "INTERNAL", focus: "Sentiment trajectory across the lifecycle." },
  { id: "reference_ability_development", name: "Reference-Ability Development", stage: "INTERNAL", focus: "From customer to referenceable advocate." },
  { id: "internal_process_improvement", name: "Internal Process Improvement", stage: "INTERNAL", focus: "Operational improvements driven by customer voice." },
  { id: "industry_specific_usecase", name: "Industry-Specific Use Case", stage: "VERTICAL", focus: "Verticalized story for a target industry." },
  { id: "company_size_segment", name: "Company Size/Segment", stage: "VERTICAL", focus: "SMB/mid-market/enterprise specific lens." },
  { id: "persona_specific_framing", name: "Persona-Specific Framing", stage: "VERTICAL", focus: "Narrative tailored by buyer persona." },
  { id: "geographic_regional_variation", name: "Geographic/Regional Variation", stage: "VERTICAL", focus: "Regional nuance and geo-specific outcomes." },
  { id: "regulated_vs_unregulated", name: "Regulated vs Unregulated", stage: "VERTICAL", focus: "How constraints differ by compliance profile." },
  { id: "public_sector_government", name: "Public Sector/Government", stage: "VERTICAL", focus: "Government procurement and compliance story." },
  { id: "before_after_transformation", name: "Before/After Transformation", stage: "FORMAT", focus: "Transformation narrative arc." },
  { id: "day_in_the_life", name: "Day-in-the-Life Story", stage: "FORMAT", focus: "Workflow-level walkthrough." },
  { id: "by_the_numbers_snapshot", name: "By-the-Numbers Snapshot", stage: "FORMAT", focus: "Data-heavy metric-led output." },
  { id: "video_testimonial_soundbite", name: "Video/Testimonial Soundbite", stage: "FORMAT", focus: "Short executive-ready quote package." },
  { id: "joint_webinar_presentation", name: "Joint Webinar/Conference", stage: "FORMAT", focus: "Talk track for co-presentations." },
  { id: "peer_reference_call_guide", name: "Peer Reference Call Guide", stage: "FORMAT", focus: "Structured peer reference call script." },
  { id: "analyst_validated_study", name: "Analyst/Third-Party Validated Study", stage: "FORMAT", focus: "Evidence pack tuned for third-party review." }
];
